import pytest
from sh305.domain.enums import UserUrgency, VehicleType
from sh305.synthetic.generator import SyntheticDataGenerator
from sh305.engine.priority import STRATEGY_WEIGHTS
from sh305.engine.controller import set_strategy
from sh305.domain.ev import EV

@pytest.fixture
def base_state():
    generator = SyntheticDataGenerator(seed=42)
    state = generator.generate_initial_system_state()
    # Clear EVs for a controlled scenario
    state.evs = []
    
    # Set grid bottleneck: Available EV capacity = 20 - 20 + 10 = 10.0 kW
    state.grid.active_limit_kw = 20.0
    state.building.appliances_demand_kw = 20.0
    state.building.total_demand_kw = 20.0
    state.solar.generation_kw = 10.0
    
    # EV1: High energy needed, late deadline (Best for SOLAR_FIRST)
    ev1 = EV(
        ev_id="EV-1",
        station_id="CS-01",
        vehicle_type=VehicleType.SUV,
        battery_capacity_kwh=100.0,
        expected_range_km=400.0,
        current_soc=20.0,
        requested_travel_distance_km=360.0,
        arrival_time=8.0,
        departure_time=18.0, # 10 hours left
        min_charging_rate_kw=1.0,
        max_charging_rate_kw=22.0,
        user_urgency=UserUrgency.MEDIUM
    )
    
    # EV2: Low energy needed, early deadline (Best for DEADLINE_FIRST and GRID_SAFETY_FIRST)
    ev2 = EV(
        ev_id="EV-2",
        station_id="CS-02",
        vehicle_type=VehicleType.HATCHBACK,
        battery_capacity_kwh=60.0,
        expected_range_km=300.0,
        current_soc=20.0,
        requested_travel_distance_km=75.0,
        arrival_time=8.0,
        departure_time=10.0, # 2 hours left
        min_charging_rate_kw=1.0,
        max_charging_rate_kw=22.0,
        user_urgency=UserUrgency.MEDIUM
    )
    
    state.stations[0].connected_ev_id = "EV-1"
    state.stations[0].occupied = True
    state.stations[1].connected_ev_id = "EV-2"
    state.stations[1].occupied = True
    
    state.evs = [ev1, ev2]
    return state

def test_strategies_exist():
    assert "DEADLINE_FIRST" in STRATEGY_WEIGHTS
    assert "SOLAR_FIRST" in STRATEGY_WEIGHTS
    assert "GRID_SAFETY_FIRST" in STRATEGY_WEIGHTS
    assert "BALANCED" not in STRATEGY_WEIGHTS

def test_strategy_produces_intended_weight_configuration():
    w_solar = STRATEGY_WEIGHTS["SOLAR_FIRST"]
    assert w_solar.w_solar_alignment > 0.0
    assert w_solar.w_energy > 1.0
    
    w_deadline = STRATEGY_WEIGHTS["DEADLINE_FIRST"]
    assert w_deadline.w_deadline > 1.0
    assert w_deadline.w_time > 1.0
    
    w_grid = STRATEGY_WEIGHTS["GRID_SAFETY_FIRST"]
    assert w_grid.w_grid_safety > 1.0

def test_strategy_change_triggers_recomputation_and_updates_state(base_state):
    set_strategy(base_state, "DEADLINE_FIRST")
    assert base_state.strategy == "DEADLINE_FIRST"
    # Allocations dict contains all stations (there are 8 generated by default)
    assert len(base_state.allocations) == 8

def test_allocations_differ_by_strategy(base_state):
    # Both EVs need high target safe power. Available EV capacity is exactly 10.0 kW.
    # So they must compete. The winner gets all 10.0 kW.
    
    # DEADLINE_FIRST: EV2 wins (deadline 10.0 vs 18.0)
    state_deadline = copy.deepcopy(base_state)
    set_strategy(state_deadline, "DEADLINE_FIRST")
    ev1_deadline = state_deadline.evs[0].current_charging_rate_kw
    ev2_deadline = state_deadline.evs[1].current_charging_rate_kw
    
    # EV2 wins
    assert ev2_deadline == 10.0
    assert ev1_deadline == 0.0
    
    # SOLAR_FIRST: EV1 wins (can absorb 8.0kW of the 10.0kW solar, vs EV2's 4.5kW)
    state_solar = copy.deepcopy(base_state)
    set_strategy(state_solar, "SOLAR_FIRST")
    ev1_sol = state_solar.evs[0].current_charging_rate_kw
    ev2_sol = state_solar.evs[1].current_charging_rate_kw
    
    # EV1 wins
    assert ev1_sol == 10.0
    assert ev2_sol == 0.0
    
    # GRID_SAFETY_FIRST: EV2 wins (requires 4.5kW vs EV1's 8.0kW, so it is safer for grid limits)
    state_grid = copy.deepcopy(base_state)
    set_strategy(state_grid, "GRID_SAFETY_FIRST")
    ev1_grid = state_grid.evs[0].current_charging_rate_kw
    ev2_grid = state_grid.evs[1].current_charging_rate_kw
    
    # EV2 wins
    assert ev2_grid == 10.0
    assert ev1_grid == 0.0
    
    # Ensure no constraint bypass was used in any strategy
    assert ev1_sol + ev2_sol <= 10.0

def test_hard_constraints_remain_valid(base_state):
    # Set tight grid constraint
    base_state.grid.active_limit_kw = 10.0
    base_state.solar.generation_kw = 0.0
    base_state.building.total_demand_kw = 0.0
    # Available = 10.0
    
    for strategy in ["DEADLINE_FIRST", "SOLAR_FIRST", "GRID_SAFETY_FIRST"]:
        set_strategy(base_state, strategy)
        total_allocation = sum(ev.current_charging_rate_kw for ev in base_state.evs)
        # Cannot exceed grid constraint
        assert total_allocation <= 10.0
        
        # Min constraint
        for ev in base_state.evs:
            if ev.current_charging_rate_kw > 0:
                assert ev.current_charging_rate_kw >= ev.min_charging_rate_kw

import copy
def test_deterministic_repeated_execution(base_state):
    state_copy_1 = copy.deepcopy(base_state)
    set_strategy(state_copy_1, "SOLAR_FIRST")
    rates_run_1 = [ev.current_charging_rate_kw for ev in state_copy_1.evs]
    
    state_copy_2 = copy.deepcopy(base_state)
    set_strategy(state_copy_2, "SOLAR_FIRST")
    rates_run_2 = [ev.current_charging_rate_kw for ev in state_copy_2.evs]
    
    assert rates_run_1 == rates_run_2
